export enum SocketMessageType {
  UNDEFINED = "UNDEFINED",
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  PING = "PING",
  PONG = "PONG",
  SPAWN_PEER_CELL = "SPAWN_PEER_CELL",
  UPDATE_PEER_CELL_POSITION = "UPDATE_PEER_CELL_POSITION",
  ICE_CANDIDATE = "ICE_CANDIDATE",
  SESSION_DESCRIPTION = "SESSION_DESCRIPTION",
  ADD_PEER = "ADD_PEER",
  REMOVE_PEER = "REMOVE_PEER",
  JOIN_CHANNEL = "JOIN_CHANNEL",
}